apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c1rl5aupu-go 
  janus-idp.io/tekton: c1rl5aupu-go
  backstage.io/kubernetes-id: c1rl5aupu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c1rl5aupu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  